Vagrant.configure("2") do |config|
  
  (2..4).each do |i|
	config.vm.define "test#{i}" do |node|
		node.vm.box = "bento/centos-6.7"
	    node.vm.hostname = "test#{i}"
	    node.vm.network :private_network, ip: "192.168.30.#{i}"
	    node.vm.provider :virtualbox do |v|
	      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
	      v.customize ["modifyvm", :id, "--memory", 512]
	      v.customize ["modifyvm", :id, "--name", "test#{i}"]
		end
	end
  end

  config.vm.provision "shell" do |s|
  	current_dir = File.dirname(__FILE__)
    ssh_pub_key = File.readlines("#{current_dir}/.ssh/id_rsa_test.pub").first.strip
    s.inline = <<-SHELL
      echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
	SHELL
  end
end
