- hosts: lb
  become: yes
  become_method: sudo

  vars:
    haproxy_app_name: mytest
    haproxy_mode: http
    haproxy_enable_stats: enable 
    haproxy_algorithm: roundrobin
    haproxy_backend_servers:
      - {name: test3, ip: 192.168.30.3, port: 8000, paramstring: check }
      - {name: test4, ip: 192.168.30.4, port: 8000, paramstring: check backup }
    haproxy_stats_users:
      - {username: test, password: test}
  
  tasks:
    - name: upgrade haproxy package
      yum: name=haproxy state=latest

    - name: Install haproxy
      yum: name=haproxy state=present

    - name: Install libselinux-python
      yum: name=libselinux-python state=present

    - name: Update HAProxy config
      template: src=templates/haproxy.template 
            dest=/etc/haproxy/haproxy.cfg 
      notify: 
        - restart haproxy

  handlers:
    - name: restart haproxy
      service: name=haproxy state=restarted


- hosts: webservers
  become: yes
  become_method: sudo

  tasks:

    - name: Install EPEL release for nginx
      yum: name=epel-release state=present

    - name: Install nginx web server
      yum: name=nginx state=installed update_cache=true

    - name: Creates directory
      file: path=/var/www/ state=directory

    - name: Install libselinux-python
      yum: name=libselinux-python state=present

    - name: local.html copy
      template: src=templates/local.html dest=/var/www/local.html mode=0644

    - name: contact.html copy
      template: src=files/contact.html dest=/var/www/contact.html mode=0644
    
    - name: Update nginx config
      template: src=templates/nginx.template 
            dest=/etc/nginx/nginx.conf 

    - name: Update default config
      template: src=templates/default.template 
            dest=/etc/nginx/conf.d/default.conf 

    - name: Hostname to local.html
      shell: echo $(hostname -f) > /var/www/local.html

    - name: Using sed to replace (bad practice)
      shell: sed -i "2s/.*/worker_processes $(echo grep ^processor /proc/cpuinfo | wc -l)/" /etc/nginx/nginx.conf

    - name: Starting nginx
      service:
        name: nginx
        state: started
